version: '3'

services:
    db:
        image: mysql:5.6
        command: ["--default-authentication-plugin=mysql_native_password"]
        env_file:
            - .env
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: docker/php7.2-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        env_file:
            - .env
        user: www-data
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            # - ${LOGS_DIR}/symfony:/var/www/symfony/var/logs
        links:
            - db
    nginx:
        build: docker/nginx
        ports:
            - ${WEB_PORT}:80
        volumes:
            - ${LOGS_DIR}/nginx/:/var/log/nginx
        links:
            - php
    elk:
        image: willdurand/elk
        ports:
            - ${ELK_PORT}:80
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    redis:
        image: redis:4

    node:
        image: node:8
        user: node
        working_dir: /var/www/symfony
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        command: bash -c "yarn && yarn dev"
