parameters:
    # Database parameters
    database_host: db
    database_port: '%env(MYSQL_PORT)%'
    database_name: '%env(MYSQL_DATABASE)%'
    database_user: '%env(MYSQL_USER)%'
    database_password: '%env(MYSQL_PASSWORD)%'

    # Mailer parameters
    mailer_transport: %env(SMTP_TRANSPORT)%
    mailer_host: '%env(SMTP_HOST)%'
    mailer_user: '%env(SMTP_USER)%'
    mailer_password: '%env(SMTP_PASSWORD)%'

    # Secret
    secret: '%env(SECRET)%'

    # Redis parameters
    redis_dsn: 'redis://%env(REDIS_DSN)%'
    redis_options: ~
    session_ttl: 86400
